# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 594b9bb16dca3fd2e02d04c7453d27cd7989dc86e45dd889246f9470ff33dea824ee9da68059ab1bd35f380f7b03fdbe79c2e4cfda42290216e9e41d7b3b90b5

test:
  secret_key_base: 1fc297507ee58b55fb31b3cfc6888224a5acc779ce368c0788133a7ef7a60b81d27d087d42561222346c9678a990e33906cab4d6cf1eadcaf8037851bf3f246f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
